name: Postman API Tests

on:
  push:
    branches: [ main ]  # Only run on pushes to the main branch

jobs:
  run-tests:
    name: Run Postman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16 (recommended)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        env:
          # Consider using secrets for environment variables
          POSTMAN_COLLECTION: ${{ secrets.POSTMAN_COLLECTION }}
          POSTMAN_ENVIRONMENT: ${{ secrets.POSTMAN_ENVIRONMENT }}
        run: |
          newman run "$POSTMAN_COLLECTION" \
            -e "$POSTMAN_ENVIRONMENT" \
            -r htmlextra \
            --reporter-htmlextra-export ./results/report.html

      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./results

      - name: Deploy test results to GitHub Pages (optional)
        if: success()  # Only deploy on successful test run
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: ./results  # Update path if results structure is different
          branch: gh-pages  # Specify the branch for published reports

          # Optional configurations (customize as needed)
          fail-on-missing-files: false  # Prevent failures due to missing files
          single-branch: true  # Deploy only to the specified branch
