# This is an intermediate workflow to help you produce a HTML extra test results report

name: "Postamn_actions Tests"
on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
   # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

    
    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
    
      
      - name: Run API Tests
        run: newman run auth.json -e qa.json" -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

   
          name: RunReports
        
