name: Postman API Tests

on:
  push:
    branches: [ main ]  # Only run on pushes to the main branch

jobs:
  run-tests:
    name: Run Postman Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://cristiancfe.github.io/postman_ci/report.html

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16 (recommended)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          newman run Auth.postman_collection.json -e QA.postman_environment.json
          -r htmlextra --reporter-htmlextra-export ./results/report.html

      - name: Upload test results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./results

      - name: Deploy test results to GitHub Pages (optional)
        if: success()  # Only deploy on successful test run
        uses: actions/deploy-pages@v1
        with:
          source: ./results  # Update path if results structure is different
          branch: gh-pages  # Specify the branch for published reports

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./results
        
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
          # Optional configurations (customize as needed)
        
