# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
stages:
    - test
postman_tests:
    stage: test
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-htmlextra
        - newman run Auth.postman_collection.json.json -e QA.postman_environment.json.json --reporters cli,htmlextra --reporter-htmlextra-export Report.html --insecure
    artifacts:
        when: always
        paths:
            - Report.html
